// ============================================================
// EKONOMIKOLLEN – Enkätens frågor (alla 20 st, sektioner A–G)
// ============================================================

import { SurveySectionMeta } from '@/types'

export const SURVEY_SECTIONS: SurveySectionMeta[] = [
  // ── SEKTION A: Grunduppgifter ─────────────────────────────
  {
    id: 'A',
    title_sv: 'Grunduppgifter om fastigheten',
    title_en: 'Basic property information',
    description_sv: 'Dessa uppgifter används som nämnare i flertalet nyckeltal. Ytuppgifter hittas i er ekonomiska plan eller årsredovisning.',
    description_en: 'These figures are used as denominators in most KPIs. Area data can be found in your financial plan or annual report.',
    questions: [
      {
        id: 'A1_year',
        type: 'number',
        label_sv: 'Vilket år avser årsredovisningen?',
        label_en: 'Which year does the annual report refer to?',
        hint_sv: 'Ange årtalet, t.ex. 2024',
        hint_en: 'Enter the year, e.g. 2024',
        unit: 'år',
        required: true,
        min: 2000,
        max: 2030,
      },
      {
        id: 'A2_apartments',
        type: 'number',
        label_sv: 'Antal lägenheter i föreningen?',
        label_en: 'Number of apartments in the association?',
        unit: 'st',
        required: true,
        min: 1,
      },
      {
        id: 'A3_brf_area_sqm',
        type: 'number',
        label_sv: 'Total bostadsrättsyta?',
        label_en: 'Total residential area?',
        hint_sv: 'Hittas i årsredovisningens förvaltningsberättelse',
        hint_en: 'Found in the board of directors report in the annual report',
        unit: 'kvm',
        required: true,
        min: 1,
      },
      {
        id: 'A4_total_area_sqm',
        type: 'number',
        label_sv: 'Total yta inkl. lokaler och garage (totalyta)?',
        label_en: 'Total area including premises and garage?',
        hint_sv: 'Inkludera alla ytor – bostäder, lokaler, garage',
        hint_en: 'Include all areas – residential, commercial, garage',
        unit: 'kvm',
        required: true,
        min: 1,
      },
      {
        id: 'A5_has_rentals',
        type: 'boolean',
        label_sv: 'Har föreningen uthyrda lokaler (butiker/kontor)?',
        label_en: 'Does the association have rented premises (shops/offices)?',
        required: true,
      },
      {
        id: 'A5b_rental_area_sqm',
        type: 'number',
        label_sv: 'Hur stor är uthyrd lokalyta?',
        label_en: 'What is the size of the rented premises?',
        hint_sv: 'Ange 0 om ej aktuellt',
        hint_en: 'Enter 0 if not applicable',
        unit: 'kvm',
        required: false,
        min: 0,
        depends_on: { field: 'A5_has_rentals', value: true },
      },
      {
        id: 'A6_land_ownership',
        type: 'select',
        label_sv: 'Äger föreningen marken eller gäller tomträtt?',
        label_en: 'Does the association own the land or is it a leasehold?',
        required: true,
        options: [
          { value: 'owns', label_sv: 'Äger marken', label_en: 'Owns the land' },
          { value: 'leasehold', label_sv: 'Tomträtt', label_en: 'Leasehold' },
          { value: 'unknown', label_sv: 'Vet ej', label_en: 'Unknown' },
        ],
      },
    ],
  },

  // ── SEKTION B: Intäkter ───────────────────────────────────
  {
    id: 'B',
    title_sv: 'Intäkter',
    title_en: 'Revenue',
    description_sv: 'Årsavgifterna är föreningens primära intäktskälla och är centrala för beräkning av räntekänslighet och avgiftsnivå.',
    description_en: 'Annual fees are the association\'s primary source of income and are central to calculating interest rate sensitivity and fee levels.',
    questions: [
      {
        id: 'B1_annual_fees',
        type: 'number',
        label_sv: 'Totala årsavgifter från medlemmar under året?',
        label_en: 'Total annual fees from members during the year?',
        hint_sv: 'Hittas i resultaträkningens intäktssida',
        hint_en: 'Found in the income statement revenue section',
        unit: 'kr',
        required: true,
        min: 0,
      },
      {
        id: 'B2_rental_income',
        type: 'number',
        label_sv: 'Intäkter från uthyrning av lokaler, garage, antenner m.m.?',
        label_en: 'Revenue from renting premises, garage, antennas, etc.?',
        hint_sv: 'Ange 0 om ej aktuellt',
        hint_en: 'Enter 0 if not applicable',
        unit: 'kr',
        required: true,
        min: 0,
      },
    ],
  },

  // ── SEKTION C: Lån och räntor ─────────────────────────────
  {
    id: 'C',
    title_sv: 'Lån och räntor',
    title_en: 'Loans and interest',
    description_sv: 'Låneskulden är avgörande för att beräkna räntekänslighet och belåningsgrad. Uppgifterna finns i balansräkningens skuldsida.',
    description_en: 'The loan debt is crucial for calculating interest rate sensitivity and leverage. This information is found in the balance sheet liabilities.',
    questions: [
      {
        id: 'C1_total_debt',
        type: 'number',
        label_sv: 'Föreningens totala räntebärande låneskuld?',
        label_en: 'The association\'s total interest-bearing loan debt?',
        hint_sv: 'Summan av alla lån i balansräkningen',
        hint_en: 'Sum of all loans in the balance sheet',
        unit: 'kr',
        required: true,
        min: 0,
      },
      {
        id: 'C2_interest_costs',
        type: 'number',
        label_sv: 'Totala räntekostnader under året?',
        label_en: 'Total interest costs during the year?',
        hint_sv: 'Hittas i resultaträkningens finansiella kostnader',
        hint_en: 'Found in the income statement financial expenses',
        unit: 'kr',
        required: true,
        min: 0,
      },
      {
        id: 'C3_avg_interest_rate',
        type: 'number',
        label_sv: 'Genomsnittlig ränta på befintliga lån (om känd)?',
        label_en: 'Average interest rate on existing loans (if known)?',
        hint_sv: 'Lämna blankt om okänd',
        hint_en: 'Leave blank if unknown',
        unit: '%',
        required: false,
        min: 0,
        max: 30,
      },
    ],
  },

  // ── SEKTION D: Energi och drift ───────────────────────────
  {
    id: 'D',
    title_sv: 'Energi och drift',
    title_en: 'Energy and operations',
    description_sv: 'Energikostnaden per kvm visar föreningens energieffektivitet och kan jämföras med er energideklaration.',
    description_en: 'Energy cost per sqm shows the association\'s energy efficiency and can be compared to your energy declaration.',
    questions: [
      {
        id: 'D1_energy_costs',
        type: 'number',
        label_sv: 'Totala kostnader för värme, el och vatten under året?',
        label_en: 'Total costs for heating, electricity and water during the year?',
        hint_sv: 'Summera alla energi- och vattenkostnader',
        hint_en: 'Sum all energy and water costs',
        unit: 'kr',
        required: true,
        min: 0,
      },
    ],
  },

  // ── SEKTION E: Underhåll och sparande ────────────────────
  {
    id: 'E',
    title_sv: 'Underhåll och sparande',
    title_en: 'Maintenance and savings',
    description_sv: 'E4 och E5 är nödvändiga för att beräkna justerat resultat, vilket ingår i nyckeltal 4 (Sparande per kvm). Uppgifterna finns i resultaträkningens noter.',
    description_en: 'E4 and E5 are necessary to calculate adjusted result, which is included in KPI 4 (Savings per sqm). Data is found in the income statement notes.',
    questions: [
      {
        id: 'E1_has_maintenance_plan',
        type: 'boolean',
        label_sv: 'Har föreningen en godkänd underhållsplan?',
        label_en: 'Does the association have an approved maintenance plan?',
        required: true,
      },
      {
        id: 'E2_maintenance_plan_year',
        type: 'number',
        label_sv: 'Vilket år upprättades eller uppdaterades underhållsplanen senast?',
        label_en: 'What year was the maintenance plan last established or updated?',
        hint_sv: 'Hoppa över om nej på föregående fråga',
        hint_en: 'Skip if no to previous question',
        unit: 'år',
        required: false,
        min: 1990,
        max: 2030,
        depends_on: { field: 'E1_has_maintenance_plan', value: true },
      },
      {
        id: 'E3_fund_allocation',
        type: 'number',
        label_sv: 'Årets avsättning till underhållsfond?',
        label_en: 'This year\'s allocation to the maintenance fund?',
        unit: 'kr',
        required: true,
        min: 0,
      },
      {
        id: 'E4_depreciation',
        type: 'number',
        label_sv: 'Årets avskrivningar?',
        label_en: 'This year\'s depreciation?',
        hint_sv: 'Hittas i noter till resultaträkningen',
        hint_en: 'Found in the notes to the income statement',
        unit: 'kr',
        required: true,
        min: 0,
      },
      {
        id: 'E5_planned_maintenance_costs',
        type: 'number',
        label_sv: 'Årets kostnadsförda planerade underhåll?',
        label_en: 'This year\'s expensed planned maintenance?',
        hint_sv: 'Hittas i noter till resultaträkningen',
        hint_en: 'Found in the notes to the income statement',
        unit: 'kr',
        required: true,
        min: 0,
      },
    ],
  },

  // ── SEKTION F: Resultat och kassaflöde ───────────────────
  {
    id: 'F',
    title_sv: 'Resultat och kassaflöde',
    title_en: 'Results and cash flow',
    description_sv: 'Årets resultat hämtas från resultaträkningens sista rad. Kassaflödesanalysen är numera obligatorisk i årsredovisningen.',
    description_en: 'The annual result is taken from the last line of the income statement. The cash flow analysis is now mandatory in the annual report.',
    questions: [
      {
        id: 'F1_net_result',
        type: 'number',
        label_sv: 'Årets resultat?',
        label_en: 'Annual result?',
        hint_sv: 'Negativt värde är tillåtet och vanligt',
        hint_en: 'Negative value is allowed and common',
        unit: 'kr',
        required: true,
      },
      {
        id: 'F2_cashflow',
        type: 'select',
        label_sv: 'Var kassaflödet för verksamhetsåret positivt eller negativt?',
        label_en: 'Was the cash flow for the fiscal year positive or negative?',
        required: true,
        options: [
          { value: 'positive', label_sv: 'Positivt', label_en: 'Positive' },
          { value: 'negative', label_sv: 'Negativt', label_en: 'Negative' },
          { value: 'unknown', label_sv: 'Vet ej', label_en: 'Unknown' },
        ],
      },
      {
        id: 'F3_cashflow_plan',
        type: 'text',
        label_sv: 'Om negativt – finns en plan för att åtgärda detta?',
        label_en: 'If negative – is there a plan to address this?',
        hint_sv: 'Beskriv kort i max 3 meningar',
        hint_en: 'Describe briefly in max 3 sentences',
        required: false,
        depends_on: { field: 'F2_cashflow', value: 'negative' },
      },
    ],
  },

  // ── SEKTION G: Styrelsens bedömning ──────────────────────
  {
    id: 'G',
    title_sv: 'Styrelsens bedömning',
    title_en: 'Board assessment',
    description_sv: 'Dessa frågor kompletterar sifferunderlaget med styrelsens egna bedömningar och framtidsplaner.',
    description_en: 'These questions supplement the financial data with the board\'s own assessments and future plans.',
    questions: [
      {
        id: 'G1_financial_assessment',
        type: 'scale',
        label_sv: 'Hur bedömer du föreningens ekonomiska situation just nu?',
        label_en: 'How do you assess the association\'s current financial situation?',
        required: true,
        min: 1,
        max: 5,
        options: [
          { value: '1', label_sv: '1 – Mycket ansträngd', label_en: '1 – Very strained' },
          { value: '2', label_sv: '2 – Ansträngd', label_en: '2 – Strained' },
          { value: '3', label_sv: '3 – Neutral', label_en: '3 – Neutral' },
          { value: '4', label_sv: '4 – God', label_en: '4 – Good' },
          { value: '5', label_sv: '5 – Mycket god', label_en: '5 – Very good' },
        ],
      },
      {
        id: 'G2_fee_increase',
        type: 'select',
        label_sv: 'Är en avgiftshöjning planerad eller diskuterad inom 2 år?',
        label_en: 'Is a fee increase planned or discussed within 2 years?',
        required: true,
        options: [
          { value: 'planned', label_sv: 'Ja, planerad', label_en: 'Yes, planned' },
          { value: 'discussed', label_sv: 'Diskuteras', label_en: 'Being discussed' },
          { value: 'no', label_sv: 'Nej', label_en: 'No' },
        ],
      },
      {
        id: 'G3_investments',
        type: 'text',
        label_sv: 'Har föreningen genomfört eller planerat några stora investeringar eller renoveringar de närmaste 5 åren?',
        label_en: 'Has the association carried out or planned any major investments or renovations in the next 5 years?',
        hint_sv: 'Beskriv kort vad som planeras',
        hint_en: 'Briefly describe what is planned',
        required: false,
      },
    ],
  },
]
